// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// hello
void hello();
RcppExport SEXP bigalgebra_hello() {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        hello();
    }
    return R_NilValue;
END_RCPP
}
// dgemm_wrapper
SEXP dgemm_wrapper(SEXP TRANSA, SEXP TRANSB, SEXP M, SEXP N, SEXP K, SEXP ALPHA, SEXP A, SEXP LDA, SEXP B, SEXP LDB, SEXP BETA, SEXP C, SEXP LDC, SEXP A_isBM, SEXP B_isBM, SEXP C_isBM, SEXP C_offset);
RcppExport SEXP bigalgebra_dgemm_wrapper(SEXP TRANSASEXP, SEXP TRANSBSEXP, SEXP MSEXP, SEXP NSEXP, SEXP KSEXP, SEXP ALPHASEXP, SEXP ASEXP, SEXP LDASEXP, SEXP BSEXP, SEXP LDBSEXP, SEXP BETASEXP, SEXP CSEXP, SEXP LDCSEXP, SEXP A_isBMSEXP, SEXP B_isBMSEXP, SEXP C_isBMSEXP, SEXP C_offsetSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type TRANSA(TRANSASEXP );
        Rcpp::traits::input_parameter< SEXP >::type TRANSB(TRANSBSEXP );
        Rcpp::traits::input_parameter< SEXP >::type M(MSEXP );
        Rcpp::traits::input_parameter< SEXP >::type N(NSEXP );
        Rcpp::traits::input_parameter< SEXP >::type K(KSEXP );
        Rcpp::traits::input_parameter< SEXP >::type ALPHA(ALPHASEXP );
        Rcpp::traits::input_parameter< SEXP >::type A(ASEXP );
        Rcpp::traits::input_parameter< SEXP >::type LDA(LDASEXP );
        Rcpp::traits::input_parameter< SEXP >::type B(BSEXP );
        Rcpp::traits::input_parameter< SEXP >::type LDB(LDBSEXP );
        Rcpp::traits::input_parameter< SEXP >::type BETA(BETASEXP );
        Rcpp::traits::input_parameter< SEXP >::type C(CSEXP );
        Rcpp::traits::input_parameter< SEXP >::type LDC(LDCSEXP );
        Rcpp::traits::input_parameter< SEXP >::type A_isBM(A_isBMSEXP );
        Rcpp::traits::input_parameter< SEXP >::type B_isBM(B_isBMSEXP );
        Rcpp::traits::input_parameter< SEXP >::type C_isBM(C_isBMSEXP );
        Rcpp::traits::input_parameter< SEXP >::type C_offset(C_offsetSEXP );
        SEXP __result = dgemm_wrapper(TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC, A_isBM, B_isBM, C_isBM, C_offset);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// daxpy_wrapper
SEXP daxpy_wrapper(SEXP N, SEXP A, SEXP X, SEXP Y, SEXP X_isBM);
RcppExport SEXP bigalgebra_daxpy_wrapper(SEXP NSEXP, SEXP ASEXP, SEXP XSEXP, SEXP YSEXP, SEXP X_isBMSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type N(NSEXP );
        Rcpp::traits::input_parameter< SEXP >::type A(ASEXP );
        Rcpp::traits::input_parameter< SEXP >::type X(XSEXP );
        Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP );
        Rcpp::traits::input_parameter< SEXP >::type X_isBM(X_isBMSEXP );
        SEXP __result = daxpy_wrapper(N, A, X, Y, X_isBM);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dpotrf_wrapper
SEXP dpotrf_wrapper(SEXP UPLO, SEXP N, SEXP A, SEXP LDA, SEXP INFO, SEXP A_isBM);
RcppExport SEXP bigalgebra_dpotrf_wrapper(SEXP UPLOSEXP, SEXP NSEXP, SEXP ASEXP, SEXP LDASEXP, SEXP INFOSEXP, SEXP A_isBMSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type UPLO(UPLOSEXP );
        Rcpp::traits::input_parameter< SEXP >::type N(NSEXP );
        Rcpp::traits::input_parameter< SEXP >::type A(ASEXP );
        Rcpp::traits::input_parameter< SEXP >::type LDA(LDASEXP );
        Rcpp::traits::input_parameter< SEXP >::type INFO(INFOSEXP );
        Rcpp::traits::input_parameter< SEXP >::type A_isBM(A_isBMSEXP );
        SEXP __result = dpotrf_wrapper(UPLO, N, A, LDA, INFO, A_isBM);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dadd_wrapper
SEXP dadd_wrapper(SEXP ALPHA, SEXP Y, SEXP Y_isBM, SEXP SIGN);
RcppExport SEXP bigalgebra_dadd_wrapper(SEXP ALPHASEXP, SEXP YSEXP, SEXP Y_isBMSEXP, SEXP SIGNSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type ALPHA(ALPHASEXP );
        Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP );
        Rcpp::traits::input_parameter< SEXP >::type Y_isBM(Y_isBMSEXP );
        Rcpp::traits::input_parameter< SEXP >::type SIGN(SIGNSEXP );
        SEXP __result = dadd_wrapper(ALPHA, Y, Y_isBM, SIGN);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dgeqrf_wrapper
SEXP dgeqrf_wrapper(SEXP Y, SEXP Q, SEXP R);
RcppExport SEXP bigalgebra_dgeqrf_wrapper(SEXP YSEXP, SEXP QSEXP, SEXP RSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP );
        Rcpp::traits::input_parameter< SEXP >::type Q(QSEXP );
        Rcpp::traits::input_parameter< SEXP >::type R(RSEXP );
        SEXP __result = dgeqrf_wrapper(Y, Q, R);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dgeemm_wrapper
SEXP dgeemm_wrapper(SEXP X, SEXP Y, SEXP X_isBM);
RcppExport SEXP bigalgebra_dgeemm_wrapper(SEXP XSEXP, SEXP YSEXP, SEXP X_isBMSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type X(XSEXP );
        Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP );
        Rcpp::traits::input_parameter< SEXP >::type X_isBM(X_isBMSEXP );
        SEXP __result = dgeemm_wrapper(X, Y, X_isBM);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dgeemd_wrapper
SEXP dgeemd_wrapper(SEXP X, SEXP Y, SEXP X_isBM);
RcppExport SEXP bigalgebra_dgeemd_wrapper(SEXP XSEXP, SEXP YSEXP, SEXP X_isBMSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type X(XSEXP );
        Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP );
        Rcpp::traits::input_parameter< SEXP >::type X_isBM(X_isBMSEXP );
        SEXP __result = dgeemd_wrapper(X, Y, X_isBM);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dgesmd_wrapper
SEXP dgesmd_wrapper(SEXP A, SEXP Y, SEXP Y_isBM, int ALPHA_LHS);
RcppExport SEXP bigalgebra_dgesmd_wrapper(SEXP ASEXP, SEXP YSEXP, SEXP Y_isBMSEXP, SEXP ALPHA_LHSSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type A(ASEXP );
        Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP );
        Rcpp::traits::input_parameter< SEXP >::type Y_isBM(Y_isBMSEXP );
        Rcpp::traits::input_parameter< int >::type ALPHA_LHS(ALPHA_LHSSEXP );
        SEXP __result = dgesmd_wrapper(A, Y, Y_isBM, ALPHA_LHS);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dgepow_wrapper
SEXP dgepow_wrapper(SEXP EXP, SEXP Y);
RcppExport SEXP bigalgebra_dgepow_wrapper(SEXP EXPSEXP, SEXP YSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type EXP(EXPSEXP );
        Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP );
        SEXP __result = dgepow_wrapper(EXP, Y);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dgeclog_wrapper
SEXP dgeclog_wrapper(SEXP Y);
RcppExport SEXP bigalgebra_dgeclog_wrapper(SEXP YSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP );
        SEXP __result = dgeclog_wrapper(Y);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dgelog_wrapper
SEXP dgelog_wrapper(SEXP BASE, SEXP Y);
RcppExport SEXP bigalgebra_dgelog_wrapper(SEXP BASESEXP, SEXP YSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type BASE(BASESEXP );
        Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP );
        SEXP __result = dgelog_wrapper(BASE, Y);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dgeexp_wrapper
SEXP dgeexp_wrapper(SEXP Y);
RcppExport SEXP bigalgebra_dgeexp_wrapper(SEXP YSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP );
        SEXP __result = dgeexp_wrapper(Y);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dgetanh_wrapper
SEXP dgetanh_wrapper(SEXP Y);
RcppExport SEXP bigalgebra_dgetanh_wrapper(SEXP YSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP );
        SEXP __result = dgetanh_wrapper(Y);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dgecosh_wrapper
SEXP dgecosh_wrapper(SEXP Y);
RcppExport SEXP bigalgebra_dgecosh_wrapper(SEXP YSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP );
        SEXP __result = dgecosh_wrapper(Y);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dgesinh_wrapper
SEXP dgesinh_wrapper(SEXP Y);
RcppExport SEXP bigalgebra_dgesinh_wrapper(SEXP YSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP );
        SEXP __result = dgesinh_wrapper(Y);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
