# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib bigalgebra
#' @importFrom Rcpp evalCpp
#' @export
hello <- function() {
    invisible(.Call('bigalgebra_hello', PACKAGE = 'bigalgebra'))
}

dgemm_wrapper <- function(TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC, A_isBM, B_isBM, C_isBM, C_offset) {
    .Call('bigalgebra_dgemm_wrapper', PACKAGE = 'bigalgebra', TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC, A_isBM, B_isBM, C_isBM, C_offset)
}

daxpy_wrapper <- function(N, A, X, Y, X_isBM) {
    .Call('bigalgebra_daxpy_wrapper', PACKAGE = 'bigalgebra', N, A, X, Y, X_isBM)
}

dpotrf_wrapper <- function(UPLO, N, A, LDA, INFO, A_isBM) {
    .Call('bigalgebra_dpotrf_wrapper', PACKAGE = 'bigalgebra', UPLO, N, A, LDA, INFO, A_isBM)
}

dadd_wrapper <- function(ALPHA, Y, Y_isBM, SIGN) {
    .Call('bigalgebra_dadd_wrapper', PACKAGE = 'bigalgebra', ALPHA, Y, Y_isBM, SIGN)
}

dgeqrf_wrapper <- function(Y, Q, R) {
    .Call('bigalgebra_dgeqrf_wrapper', PACKAGE = 'bigalgebra', Y, Q, R)
}

dgeemm_wrapper <- function(X, Y, X_isBM) {
    .Call('bigalgebra_dgeemm_wrapper', PACKAGE = 'bigalgebra', X, Y, X_isBM)
}

dgeemd_wrapper <- function(X, Y, X_isBM) {
    .Call('bigalgebra_dgeemd_wrapper', PACKAGE = 'bigalgebra', X, Y, X_isBM)
}

dgesmd_wrapper <- function(A, Y, Y_isBM, ALPHA_LHS) {
    .Call('bigalgebra_dgesmd_wrapper', PACKAGE = 'bigalgebra', A, Y, Y_isBM, ALPHA_LHS)
}

dgepow_wrapper <- function(EXP, Y) {
    .Call('bigalgebra_dgepow_wrapper', PACKAGE = 'bigalgebra', EXP, Y)
}

dgeclog_wrapper <- function(Y) {
    .Call('bigalgebra_dgeclog_wrapper', PACKAGE = 'bigalgebra', Y)
}

dgelog_wrapper <- function(BASE, Y) {
    .Call('bigalgebra_dgelog_wrapper', PACKAGE = 'bigalgebra', BASE, Y)
}

dgeexp_wrapper <- function(Y) {
    .Call('bigalgebra_dgeexp_wrapper', PACKAGE = 'bigalgebra', Y)
}

dgetanh_wrapper <- function(Y) {
    .Call('bigalgebra_dgetanh_wrapper', PACKAGE = 'bigalgebra', Y)
}

dgecosh_wrapper <- function(Y) {
    .Call('bigalgebra_dgecosh_wrapper', PACKAGE = 'bigalgebra', Y)
}

dgesinh_wrapper <- function(Y) {
    .Call('bigalgebra_dgesinh_wrapper', PACKAGE = 'bigalgebra', Y)
}

